# YAZI SCRATCHPAD

windowrulev2 = workspace special:yazi, class:^(scratch-yazi)$
windowrulev2 = size 900 700, class:^(scratch-yazi)$

bind = ALT, E, exec, ~/.local/bin/scratchpad-toggle yazi scratch-yazi "kitty --class scratch-yazi -e yazi"

